# Generated by Django 5.0.7 on 2024-07-26 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
