# Generated by Django 5.0.7 on 2024-07-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='depreciation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
