# Generated by Django 5.0.7 on 2024-07-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_user_email_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
    ]
